module(
    name = "pyrefly.bzl",
    version = "0.1.0",
)

bazel_dep(name = "rules_python", version = "2.0.0")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_pycross", version = "2.0.0-alpha.2")

bazel_dep(name = "rules_shell", version = "0.8.0", dev_dependency = True)
bazel_dep(name = "rules_testing", version = "0.9.0", dev_dependency = True)
bazel_dep(name = "bazel_lib", version = "3.2.0", dev_dependency = True)
bazel_dep(name = "stardoc", version = "0.8.1", dev_dependency = True)
bazel_dep(
    name = "rules_bazel_integration_test",
    version = "0.37.1",
    dev_dependency = True,
)
bazel_dep(name = "pyrefly_test_targets", version = "0.0.0", dev_dependency = True)
bazel_dep(name = "pyrefly_testlib", version = "0.0.0", dev_dependency = True)

local_path_override(
    module_name = "pyrefly_test_targets",
    path = "tests/external_targets",
)

local_path_override(
    module_name = "pyrefly_testlib",
    path = "tests/testlib",
)

bazel_binaries = use_extension(
    "@rules_bazel_integration_test//:extensions.bzl",
    "bazel_binaries",
    dev_dependency = True,
)
bazel_binaries.download(version_file = "//:.bazelversion")
use_repo(bazel_binaries, "bazel_binaries", "bazel_binaries_bazelisk", "build_bazel_bazel_.bazelversion")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.13.11",
)

pycross = use_extension(
    "@rules_pycross//pycross/extensions:pycross.bzl",
    "pycross",
    dev_dependency = True,
)
pycross.configure_toolchains(
    platforms = [
        "aarch64-apple-darwin",
        "aarch64-unknown-linux-gnu",
        "x86_64-apple-darwin",
        "x86_64-unknown-linux-gnu",
    ],
    python_versions = ["3.13.11"],
)

uv = use_extension(
    "@rules_pycross//pycross/extensions:uv.bzl",
    "uv",
)
uv.workspace(
    name = "pyrefly_pypi",
    lock_file = "//:uv.lock",
)
uv.repo(
    workspace = "pyrefly_pypi",
)
use_repo(uv, "pyrefly_pypi")

pyrefly = use_extension("//:pyrefly.bzl", "pyrefly", dev_dependency = True)
pyrefly.toolchain(
    version = "1.1.1",
)
use_repo(pyrefly, "pyrefly_toolchain")

register_toolchains(
    "@pyrefly_toolchain//:all",
    dev_dependency = True,
)

register_toolchains(
    "//tests/analysis/target_environment_toolchains:all",
    dev_dependency = True,
)
