[project]
name = "pyrefly-bzl"
version = "0.2.0"
requires-python = ">=3.11"
dependencies = [
  "opentelemetry-exporter-otlp-json-file==0.65b0",
  "opentelemetry-sdk==1.44.0",
  "simple-parsing==0.1.8",
  "tomli-w==1.2.0",
]

[tool.pyrefly]
baseline-format = "minimal"

[tool.pyrefly.errors]
unused-ignore = "error"
