load("@rules_python//python:defs.bzl", "py_library")
load("//:pyrefly_aspects.bzl", "pyrefly_check_test")

py_library(
    name = "consumer",
    testonly = True,
    srcs = ["consumer.py"],
    tags = ["manual"],
    deps = [":fixture"],
)

py_library(
    name = "fixture",
    testonly = True,
    srcs = ["fixture.py"],
)

pyrefly_check_test(
    name = "test",
    target = ":fixture",
)
