module(
    name = "pyrefly_rules_pycross_fixture",
    version = "0.0.0",
)

bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "pyrefly.bzl", version = "0.1.0")

bazel_dep(name = "pyrefly_integration_testlib", version = "0.0.0", dev_dependency = True)
bazel_dep(name = "pyrefly_testlib", version = "0.0.0", dev_dependency = True)

bazel_dep(name = "rules_pycross", version = "2.0.0-alpha.2")
bazel_dep(name = "rules_python", version = "2.0.0")

local_path_override(
    module_name = "pyrefly.bzl",
    path = "../../..",
)

local_path_override(
    module_name = "pyrefly_integration_testlib",
    path = "../testlib",
)

local_path_override(
    module_name = "pyrefly_testlib",
    path = "../../testlib",
)

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.13.11",
)

pycross = use_extension(
    "@rules_pycross//pycross/extensions:pycross.bzl",
    "pycross",
)
pycross.configure_toolchains(
    platforms = [
        "aarch64-apple-darwin",
        "x86_64-unknown-linux-gnu",
    ],
    python_versions = ["3.13.11"],
)

uv = use_extension(
    "@rules_pycross//pycross/extensions:uv.bzl",
    "uv",
)
uv.workspace(
    name = "integration_pypi",
    lock_file = "//:uv.lock",
)
uv.repo(
    workspace = "integration_pypi",
)
use_repo(uv, "integration_pypi")

pyrefly = use_extension("@pyrefly.bzl", "pyrefly")
pyrefly.toolchain(
    version = "1.1.1",
)
use_repo(pyrefly, "pyrefly_toolchain")

register_toolchains("@pyrefly_toolchain//:all")
