load("@rules_python//python:defs.bzl", "py_binary", "py_library")

filegroup(
    name = "all_files",
    srcs = glob(["*"]),
    visibility = ["//:__subpackages__"],
)

py_binary(
    name = "wrapper",
    legacy_create_init = 0,
    main_module = "pyrefly.private.wrapper",
    visibility = ["//visibility:public"],
    deps = [":wrapper_lib"],
)

py_library(
    name = "wrapper_lib",
    srcs = glob(["*.py"]),
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "@pyrefly_pypi//simple_parsing",
        "@pyrefly_pypi//tomli_w",
    ],
)
