name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: facebook/install-dotslash@v2
      - uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ runner.os }}-bazel-disk
          repository-cache: true
      - run: ./bin/dprint check
      - run: ./bin/lint.sh
      - run: ./bin/test.sh
